### ISSUE TITLE
wt4g1_wt4e1

### ISSUE THREAD

**Issue by syedyasserali** [OpenIPSL/OpenIPSL#193]
i was using wt4g_wt4e in my model using openIPSL i gave example values in the model but i was encountering error

![1w](https://user-images.githubusercontent.com/52651519/64494226-f13a1e00-d2a7-11e9-9341-b5cf378fe5b1.PNG)
![2w](https://user-images.githubusercontent.com/52651519/64494227-f13a1e00-d2a7-11e9-9c16-4b551b2b6212.PNG)
[er.docx](https://github.com/OpenIPSL/OpenIPSL/files/3588037/er.docx)

**Comment by lvanfretti** [comment]
@syedyasserali since you didn't upload your model, I have tested the example model WT4G1_WT4E1 in both Dymola and OpenModelica. It works fine in Dymola, but there is an issue in OpenModelica.

This kind of behavior we have seen before with Giuseppe Laera in a new model he is developing, and he had to spend a lot of time refactoring the code to get it to work in OpenModelica. 

I suggest you reach out to the OpenModelica team because this kind of problem will not be solved until the next release of OpenModelica, that is, if this is one of the models we have prioritized to update in a project we are doing.

My suggestion is that if the Type 4 model is not really required, you should use the PSAT DFig model.
