### ISSUE TITLE
Wrong name of ShuntR?

### ISSUE THREAD

**Issue by dietmarw** [OpenIPSL/OpenIPSL#93]
When cleaning up the icons I stumbled upon `OpenIPSL.Electrical.Banks.PwShuntR`
the description, the equations and the icon suggests this is a shunt L and not shunt R. 
Am I missing something?

**Comment by tinrabuzin** [comment]
@dietmarw It seems like you're right, i.e. by looking at the equations it seems like it's shunt reactor. But that model was developed by other project partners so I don't remember seeing anyone using it in "our" models. Moreover, we have shunt B, C and R (which is L actually). So probably they included it because you can specify shunts in different ways, which means that we should maybe recode one shunt component with different parameter specifications...

**Comment by dietmarw** [comment]
Yes having one with parameters would be an improvement. I will not change the name right now and we can leave this ticket to deal with it.

**Comment by dietmarw** [comment]
My students just wanted to *use* that model and it turns out it is actually faulty and does all kinds of things but not what it should. 

We solved the issue by using either `PwShunt` or `Simulink.PwShunt` instead. The former is still causing a division by zero which should be looked at. See also #174.

So I'm for removing `PwShuntR` and `PwShuntC` given the `PwShunt` issue #174 is resolved.

**Comment by marcelofcastro** [comment]
@dietmarw are you going to remove PwShuntC and PwShuntR from the library since issue #174 is solved?
